# EXAMPLE values.yaml
# We can create another values.yaml with different values
helm-demo-app:
  appName: demo-app

  namespace: pt-my-app

  replicaCount: 5

  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "1.27.1"

  podAnnotations: {}

  podLabels:
    app: demo-app
    owner: my-team
    region: asia-southeast2
    environment: pt

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 400m
      memory: 256Mi

  livenessProbe:
    httpGet:
      path: /
      port: http

  readinessProbe:
    httpGet:
      path: /
      port: http

  configMap:
    data:
      APP_CONCURRENCY: 1000
      APP_DEBUG: true
